services:
  sonic:
    image: valeriansaliou/sonic:v1.4.9
    volumes:
      - type: volume
        source: sonic
        target: /var/lib/sonic/store
      - type: volume
        source: sonic
        target: /etc/sonic.cfg
        volume:
          subpath: config.cfg
volumes:
  sonic:
