services:
  php-fpm-base:
    image: php-fpm-base
    build: # https://stackoverflow.com/questions/48874739/build-docker-image-that-depends-on-a-local-dockerfile/79166897#79166897
      dockerfile: Dockerfile
    entrypoint: sh -c exit
    pull_policy: build
  php-fpm:
    extends:
      file: ../common.compose.yaml
      service: common
    depends_on:
      - php-fpm-base
    image: php-fpm
    build:
      dockerfile_inline: |
        # syntax=docker/dockerfile:1
        FROM php-fpm-base

        ADD --chmod=0755 \
          https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
          /usr/local/bin
        RUN install-php-extensions $PHP_EXTENSIONS
    # https://github.com/docker-library/php/blob/6b636b96c06be449514a5033037bf653d8a86967/8.3/bullseye/fpm/Dockerfile#L275
    command: php-fpm
    ports:
      - $PHP_FPM_PORT:9000
