services:
  php-fpm:
    extends:
      file: ../common.compose.yaml
      service: common
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PHP_INI_OPEN_BASEDIR: ${PHP_INI_OPEN_BASEDIR:-}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS:-}
        PHP_INI: ${PHP_INI:-}
