name: tbm-v1
services:
  s6:
    extends:
      file: ../../../base/s6.nginx.php-fpm/compose.yaml
      service: s6
    volumes:
      - type: volume
        target: /var/www
        source: data
volumes:
  data:
