name: tbm-v1
services:
  s6:
    extends:
      file: ../../../base/s6.nginx.php-fpm/compose.yaml
      service: s6
    build:
      dockerfile: $PWD/Dockerfile
    volumes:
      - type: volume
        read_only: true
        source: data
        target: /var/www/core.php
        volume:
          subpath: core.php
      - type: volume
        read_only: true
        source: data
        target: /var/www/sitemaps
        volume:
          subpath: sitemaps
volumes:
  data:
