services:
  s6:
    extends:
      file: ../../base/s6.nginx.php-fpm/compose.yaml
      service: s6
    volumes:
      - type: bind
        source: ./s6-rc.d
        target: /s6-rc.extra.d
      - type: volume
        target: /var/www/html/config.inc.php
        source: data
        volume:
          subpath: config.inc.php
volumes:
  data:
