services:
  s6:
    extends:
      file: ../../base/s6.nginx.php-fpm/compose.yaml
      service: s6
    build:
      context: ../..
      dockerfile: srv/pma/Dockerfile
    volumes:
      - type: volume
        target: /var/www/config.inc.php
        source: data
        volume:
          subpath: config.inc.php
volumes:
  data:
