# https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/
add_header               X-Powered-By php always;
fastcgi_split_path_info  ^(.+?\.php)(/.*)$;

# https://serverfault.com/questions/627903/is-the-php-option-cgi-fix-pathinfo-really-dangerous-with-nginx-php-fpm
if (!-f $request_filename) {
    return 404;
}
try_files $uri =404;

# https://httpoxy.org
fastcgi_param  HTTP_PROXY "";

fastcgi_pass   unix:/run/php-fpm.sock;
fastcgi_index  index.php;

include        fastcgi_params;
# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#use-request-filename-for-script-filename
fastcgi_param  SCRIPT_FILENAME $request_filename;
# https://serverfault.com/questions/465607/nginx-document-rootfastcgi-script-name-vs-request-filename
# fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
