services:
  redis:
    image: redis:7.4.1
    volumes:
      - type: volume
        source: redis
        # https://github.com/docker-library/docs/tree/master/redis#start-with-persistent-storage
        target: /data
    command: redis-server --save 60 1 --loglevel warning
  queue:
    extends:
      file: ../common.compose.yaml
      service: common
    image: $COMPOSE_PROJECT_NAME-php-fpm
    command: php $WEB_ROOT/flarum queue:work
volumes:
  redis:
