services:
  redis:
    image: redis:7.4.1
  queue:
    extends:
      file: ../common/compose.yaml
      service: common
    depends_on:
      - php-fpm
    image: php-fpm
    command: php -d disable_functions $WEB_ROOT/flarum queue:work
