services:
  s6:
    extends:
      file: ../s6.nginx.php-fpm/compose.yaml
      service: s6
    build:
      context: ../..
      dockerfile: base/flarum/Dockerfile
      args:
        CRONTAB: '* * * * * php flarum schedule:run'
        NGINX_ROOT: /var/www/public
        NGINX_CONF: |
          location / {
              try_files  $$uri $$uri/ /index.php?$$query_string;
          }
    volumes:
      - type: bind
        read_only: true
        source: ./s6-rc.d
        target: /s6-rc.extra.d/flarum
      - type: volume
        source: data
        target: /mnt/flarum
      - type: volume
        source: data
        target: /var/www/public
        volume:
          subpath: public
      - type: volume
        source: data
        target: /var/www/storage/sessions
        volume:
          subpath: storage/sessions
volumes:
  data:
