location $NGINX_SUB_BASE_DIR/ {
    # https://serverfault.com/questions/674604/nginx-how-to-strip-location-prefix-in-fastcgi-script-name/690009#690009
    alias $NGINX_SUB_BASE_DIR_ALIAS;

    # https://serverfault.com/questions/455799/how-to-remove-location-block-from-uri-in-nginx-configuration/1172730#1172730
    # https://stackoverflow.com/questions/20426812/nginx-try-files-alias-directives/35102259#35102259
    try_files  $uri $uri/ $NGINX_SUB_BASE_DIR/$NGINX_SUB_BASE_DIR/index.php?$query_string;

    location ~ [^/]\.php(/|$) {
        include snippets/php-fpm.conf;
    }
}
