include:
  - ../../base/php-fpm/compose.yaml
  - ../../base/flarum/compose.yaml
  - ../../base/flarum/extra/sonic.compose.yaml
  - ../../base/flarum/extra/redis.compose.yaml
  - ../../base/flarum/extra/inotifyAdd/compose.yaml
