services:
  s6:
    extends:
      file: ../common.compose.yaml
      service: common
    ports:
      - target: 80
        published: ${NGINX_PORT:?}
        host_ip: 127.0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        CRONTAB: ${CRONTAB:-}
        PHP_INI: ${PHP_INI:-}
        PHP_INI_OPEN_BASEDIR: ${PHP_INI_OPEN_BASEDIR:-}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS:-}
        NGINX_DOMAIN: ${NGINX_DOMAIN:?}
        NGINX_ROOT: ${NGINX_ROOT:-/var/www}
        NGINX_CONF: ${NGINX_CONF:-}
        NGINX_SUB_BASE_DIR: ${NGINX_SUB_BASE_DIR:-}
        NGINX_SUB_BASE_DIR_ALIAS: ${NGINX_SUB_BASE_DIR_ALIAS:-/var/www/}
    volumes:
      - type: bind
        source: ${NGINX_CONF_EXTRA_FILE:-/dev/null}
        target: /etc/nginx/extra.conf
