# syntax=docker/dockerfile:1
# https://docs.docker.com/build/building/variables/#env-usage-example
ARG NGINX_DOMAIN
ENV NGINX_DOMAIN=$NGINX_DOMAIN
ARG NGINX_ROOT
ENV NGINX_ROOT=$NGINX_ROOT

# used by ./nginx/http.d/default.conf
ARG NGINX_CONF
ENV NGINX_CONF=$NGINX_CONF
ARG NGINX_SUB_BASE_DIR
ENV NGINX_SUB_BASE_DIR=$NGINX_SUB_BASE_DIR
ARG NGINX_SUB_BASE_DIR_ALIAS
ENV NGINX_SUB_BASE_DIR_ALIAS=$NGINX_SUB_BASE_DIR_ALIAS
