services:
  common-php-fpm:
    image: common-php-fpm
    build: # https://stackoverflow.com/questions/48874739/build-docker-image-that-depends-on-a-local-dockerfile/79166897#79166897
      dockerfile: php-fpm.Dockerfile
    entrypoint: [sh, -c, exit]
    pull_policy: build
  php-fpm:
    extends:
      file: compose.yaml
      service: common
    depends_on:
      - common-php-fpm
    image: php-fpm
    build:
      dockerfile_inline: |
        # syntax=docker/dockerfile:1
        FROM common-php-fpm

        ADD --chmod=0755 https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
        RUN <<BASH
          install-php-extensions $PHP_EXTENSIONS
          # for smtp: https://stackoverflow.com/questions/64146145/how-to-alias-a-dns-name-to-host-docker-internal-inside-a-docker-container
          echo 'echo "$(getent hosts host.docker.internal | awk '"'"'{ print $1 }'"'"')" localhost.n0099.net >> /etc/hosts' >> /etc/rc.local
        BASH
    ports:
      - $PHP_FPM_PORT:9000
