# https://gist.github.com/tsolar/8d45ed05bcff8eb75404?permalink_comment_id=3365898#gistcomment-3365898
# https://symfony.com/doc/current/setup/web_server_configuration.html
location /tbm/be/ {
    alias /var/www/be/public/;
    try_files    $uri $uri/ @tbm_be;

    location ~ ^/tbm/be/index\.php(/|$) {
        internal;
        include  snippets/php-fpm.conf;
    }

    location ~ \.php$ {
        return   404;
    }
}

location @tbm_be {
    rewrite  ^/tbm/be/.*$ /tbm/be/index.php last;
}
