services:
  nginx:
    extends:
      file: ../common.compose.yaml
      service: common
    ports:
      - target: 80
        published: $NGINX_PORT
        host_ip: 127.0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NGINX_DOMAIN: ${NGINX_DOMAIN:?}
        NGINX_ROOT: ${NGINX_ROOT:-/var/www/html}
        NGINX_CONF: ${NGINX_CONF:-}
    volumes:
      - type: bind
        source: ${NGINX_CONF_EXTRA_FILE:-/dev/null}
        target: /etc/nginx/extra.conf
