include:
  - ../../base/php-fpm/compose.yaml
services:
  cron:
    extends:
      file: ../base/cron.compose.yaml
      service: cron
    build:
      args:
        CRONTAB: '* * * * * php $WEB_ROOT/do.php'
