services:
  s6:
    extends:
      file: ../../base/s6.nginx.php-fpm/compose.yaml
      service: s6
    build:
      dockerfile: base/s6.nginx.php-fpm/vanilla.Dockerfile
      args:
        CRONTAB: '* * * * * php do.php'
    volumes:
      - type: volume
        source: data
        target: /var/www
volumes:
  data:
