services:
  s6:
    extends:
      file: ../../base/s6.nginx.php-fpm/compose.yaml
      service: s6
    build:
      dockerfile: $PWD/Dockerfile
      args:
        CRONTAB: '* * * * * php do.php'
    volumes:
      - type: bind
        read_only: true
        source: ./s6-rc.d
        target: /s6-rc.extra.d/tc
      - type: volume
        read_only: true
        source: data
        target: /mnt/tc
volumes:
  data:
