services:
  inotify-add:
    extends:
      file: ../../../common.compose.yaml
      service: common
    build:
      context: .
    init: false # https://superuser.com/questions/1829830/behavior-of-sigint-with-bash
    volumes:
      - type: volume
        source: data
        target: /var/www
