# `volume.subpath` won't work when it's an mountpoint to zfs dataset
x-volumes: &volumes
  - type: volume
    source: files_original
    target: /var/www/public/assets/filesOriginal
  - type: volume
    source: files_webp
    target: /var/www/public/assets/filesWebp
volumes:
  files_original:
  files_webp:
services:
  s6:
    volumes: *volumes
  inotify-add:
    volumes: *volumes
