services:
  inotify-add:
    extends:
      file: ../../../common.compose.yaml
      service: common
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: volume
        source: data
        target: /var/www
