services:
  inotify-add:
    extends:
      file: ../../../common.compose.yaml
      service: common
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        WEBP_VERSION: 1.5.0
    volumes:
      - type: volume
        source: data
        target: /var/www/html
